config/routes.rb
Rails.application.routes.draw do
  get 'user/index'
  post 'user/create'
  root 'user#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = email.downcase }

  validates_presence_of(:first_name, :last_name, :url, :email)

  validates_length_of :email, maximum: 255

  validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
    # create  a new instance of the user
    @user = User.new

    # fetch all the user in the DB
    @users = User.all
  end

  def create

    if validate_email.success?
      @user = user(validate_email.email)
      if @user.save
        respond_to do |format|
          format.html { redirect_to :user_index, notice: 'User was successfully created.' }
        end
      else
        redirect_to :user_index, notice: @user.errors.full_messages[0]
      end
    else
      flash[:alert] = validate_email.errors['info']
      redirect_to :user_index
    end

  end




  private

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:first_name, :last_name, :url)
  end

  def validate_email
    EmailValidator.call(user_params[:first_name], user_params[:last_name], user_params[:url])
  end

  def user(email)
    @user = User.new(user_params)
    @user.email = email
    @user
  end
end

app/helpers/application_helper.rb
require 'rest-client'

module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EmailValidation</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% flash.each do |type, msg| %>
  <div>
    <%= msg %>
  </div>
<% end %>
    <%= yield %>
  </body>
</html>

app/views/user/create.html.erb
<h1>User#create</h1>
<p>Find me in app/views/user/create.html.erb</p>

 <%= simple_form_for(@user, as: :user, method: :post, url: user_create_url) do |f| %>
        <%= f.error_notification %>

        <div class="form-inputs">
          <%= f.input :fname,
            required: true,
            autofocus: true,
            input_html: { autocomplete: "First Name" }%>
          <%= f.input :lname,
            required: true,
            autofocus: true,
            input_html: { autocomplete: "Last Name" }%>
          <%= f.input :username,
            required: true,
            autofocus: true,
            input_html: { autocomplete: "Username" }%>
          <%= f.input :email,
            required: true,
            autofocus: true,
            input_html: { autocomplete: "email" }%>
          <%= f.input :password,
                required: true,
                hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length),
                input_html: { autocomplete: "new-password" } %>
              <%= f.input :password_confirmation,
                required: true,
                input_html: { autocomplete: "new-password" } %>
        </div>

        <div class="form-actions">
          <%= f.button :submit, "Sign up", class: 'btn btn-info' %>
        </div>
      <% end %>

app/views/user/index.html.erb
<div class="app">
  <%= simple_form_for(@user, as: :user, method: :post, url: user_create_url) do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <%= f.input :first_name,
        required: true,
        autofocus: true,
        placeholder: 'last_name',
        input_html: { autocomplete: "First Name" }%>
      <%= f.input :last_name,
        required: true,
        autofocus: true,
        placeholder: 'last_name',
        input_html: { autocomplete: "Last Name" }%>
      <%= f.input :url,
      required: true,
      autofocus: true,
      placeholder: 'url',
      input_html: { autocomplete: "url" }%>
    </div>

    <div class="form-actions">
      <%= f.button :submit, "Sign up", class: 'btn btn-info' %>
    </div>
  <% end %>

  <h2> Valid emails</h2>
  <table class="user-table">
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Url</th>
      <th>Email</th>
    </tr>
    <% @users&.each_with_index do |user, index| %>
      <tr>
        <td><%= user.first_name %>
        <td><%= user.last_name %></td>
        <td><%= user.url %></td>
        <td><%= user.email %></td>
      </tr>
    <% end %>
  </table>
</div>